import type { RuleMeta } from "../../rules/types.js";

const AGENT = "web-hardener";
const STATIC = ["static"] as const;
const LIVE = ["live"] as const;

/** Catalog entries for every rule this agent can raise. Keep in sync with the agent's ruleIds. */
export const RULES: readonly RuleMeta[] = [
  {
    id: "WEB-001",
    agent: AGENT,
    title: "Production source maps are enabled",
    severity: "low",
    cwe: "CWE-540",
    owasp: "A05",
    summary: "The build config publishes source maps in production, letting anyone download and read your original source code, comments and internal routes.",
    fix: "Disable production source maps (productionSourceMap false, build.sourcemap false) or upload them privately to your error tracker.",
    modes: STATIC,
    tags: ["config", "info-disclosure"],
  },
  {
    id: "WEB-002",
    agent: AGENT,
    title: "CORS allows any origin to make credentialed requests",
    severity: "high",
    cwe: "CWE-942",
    owasp: "A05",
    summary: "The CORS configuration reflects or allows every origin together with credentials, so any website a logged-in user visits can read authenticated responses from your API.",
    fix: "Replace the wildcard or reflected origin with an explicit allow-list of trusted origins.",
    modes: STATIC,
    tags: ["cors", "config"],
  },
  {
    id: "WEB-003",
    agent: AGENT,
    title: "Unsanitized value written into the page",
    severity: "high",
    cwe: "CWE-79",
    owasp: "A03",
    summary: "A value is written into the DOM with an HTML sink such as dangerouslySetInnerHTML or innerHTML without sanitization, so attacker-controlled content can run script in your users' browsers (XSS).",
    fix: "Render text instead of HTML, or sanitize with a vetted library such as DOMPurify before using an HTML sink.",
    modes: STATIC,
    tags: ["xss"],
  },
  {
    id: "WEB-004",
    agent: AGENT,
    title: "Next.js app does not configure security headers",
    severity: "low",
    cwe: "CWE-693",
    owasp: "A05",
    summary: "The Next.js project sets no security headers (CSP, frame protection, nosniff, referrer policy), leaving browsers' built-in defenses switched off.",
    fix: "Add a headers() block in next.config or middleware that sets Content-Security-Policy, X-Content-Type-Options, frame-ancestors and Referrer-Policy.",
    modes: STATIC,
    tags: ["headers", "nextjs"],
  },
  {
    id: "WEB-006",
    agent: AGENT,
    title: "File write uses an attacker-controlled name with no sanitization",
    severity: "high",
    cwe: "CWE-22",
    owasp: "A01",
    summary: "A file write builds its path from a name the client controls, such as an uploaded file's name, without stripping traversal segments. An attacker can write outside the intended folder and overwrite code or config.",
    fix: "Generate the stored file name yourself or reduce the input with path.basename, and verify the resolved path stays inside the upload directory.",
    modes: STATIC,
    tags: ["path-traversal", "upload"],
  },
  {
    id: "WEB-007",
    agent: AGENT,
    title: "Next.js image optimizer accepts images from any host",
    severity: "medium",
    cwe: "CWE-918",
    owasp: "A05",
    summary: "images.remotePatterns (or domains) allows every hostname, so /_next/image fetches and re-serves any URL an attacker supplies: a free image proxy on your bill, content laundering under your domain, and a way to probe internal addresses.",
    fix: "List the exact hostnames and path prefixes your app loads images from.",
    modes: STATIC,
    tags: ["config","nextjs","ssrf"],
  },
  {
    id: "WEB-008",
    agent: AGENT,
    title: "Next.js image optimizer serves SVG without a sandbox",
    severity: "medium",
    cwe: "CWE-79",
    owasp: "A03",
    summary: "dangerouslyAllowSVG is enabled without a sandboxing contentSecurityPolicy and contentDispositionType 'attachment', so an SVG opened directly can run script on your origin.",
    fix: "Add contentDispositionType: 'attachment' and a CSP with sandbox next to dangerouslyAllowSVG, or drop it.",
    modes: STATIC,
    tags: ["config","nextjs","xss"],
  },
  {
    id: "WEB-009",
    agent: AGENT,
    title: "Message listener does not check the sender's origin",
    severity: "medium",
    cwe: "CWE-346",
    owasp: "A01",
    summary: "A window 'message' handler uses event.data without comparing event.origin to your own origin or an allowlist, so any page that can open or frame your site can drive the handler with crafted messages.",
    fix: "Check event.origin against an exact allowlist before using event.data, and validate the message shape.",
    modes: STATIC,
    tags: ["xss","postmessage"],
  },
  {
    id: "WEB-010",
    agent: AGENT,
    title: "Token or session data sent with postMessage to any origin",
    severity: "high",
    cwe: "CWE-201",
    owasp: "A02",
    summary: "postMessage is called with targetOrigin '*' and a payload containing a token, session or auth value, so whichever page occupies the target window receives the credential.",
    fix: "Pass the exact receiving origin instead of '*'.",
    modes: STATIC,
    tags: ["postmessage","secrets"],
  },
  {
    id: "WEB-011",
    agent: AGENT,
    title: "Error details returned to clients",
    severity: "medium",
    cwe: "CWE-209",
    owasp: "A05",
    summary: "A request handler returns the caught error (message, stack or the whole object) in the HTTP response, leaking file paths, SQL and SDK internals to attackers. Stack traces are rated high.",
    fix: "Log the error on the server and return a generic message; expose only messages from your own safe error classes.",
    modes: STATIC,
    tags: ["info-disclosure","errors"],
  },
  {
    id: "WEB-L01",
    agent: AGENT,
    title: "Content-Security-Policy header missing or weak",
    severity: "medium",
    cwe: "CWE-693",
    owasp: "A05",
    summary: "The live site sends no Content-Security-Policy, or one that allows unsafe-inline, unsafe-eval or wildcard script sources, so one injected script becomes account takeover.",
    fix: "Send a CSP with a restrictive script-src (nonces or hashes) and no unsafe-inline, unsafe-eval or wildcard sources.",
    modes: LIVE,
    tags: ["headers"],
  },
  {
    id: "WEB-L02",
    agent: AGENT,
    title: "Strict-Transport-Security header missing or too short",
    severity: "low",
    cwe: "CWE-319",
    owasp: "A02",
    summary: "The site does not send HSTS, or its max-age is short, so browsers may first connect over plain HTTP where a network attacker can downgrade or intercept the session.",
    fix: "Send Strict-Transport-Security with a long max-age (at least 180 days), ideally with includeSubDomains.",
    modes: LIVE,
    tags: ["headers", "tls"],
  },
  {
    id: "WEB-L03",
    agent: AGENT,
    title: "Clickjacking protection missing",
    severity: "low",
    cwe: "CWE-1021",
    owasp: "A05",
    summary: "The site sends neither X-Frame-Options nor a CSP frame-ancestors directive, so another site can embed it in an invisible frame and trick users into clicking.",
    fix: "Send X-Frame-Options: DENY (or SAMEORIGIN) or a CSP frame-ancestors directive.",
    modes: LIVE,
    tags: ["headers"],
  },
  {
    id: "WEB-L04",
    agent: AGENT,
    title: "X-Content-Type-Options header missing",
    severity: "low",
    cwe: "CWE-693",
    owasp: "A05",
    summary: "Without X-Content-Type-Options: nosniff, browsers may guess file types and execute uploaded content as script.",
    fix: "Send X-Content-Type-Options: nosniff on all responses.",
    modes: LIVE,
    tags: ["headers"],
  },
  {
    id: "WEB-L05",
    agent: AGENT,
    title: "Referrer-Policy header missing",
    severity: "low",
    cwe: "CWE-200",
    owasp: "A05",
    summary: "Without a Referrer-Policy, full URLs (which can contain tokens or ids) may leak to other sites through the Referer header.",
    fix: "Send Referrer-Policy: strict-origin-when-cross-origin (or stricter).",
    modes: LIVE,
    tags: ["headers"],
  },
  {
    id: "WEB-L06",
    agent: AGENT,
    title: "Permissions-Policy header missing",
    severity: "low",
    cwe: "CWE-693",
    owasp: "A05",
    summary: "Without a Permissions-Policy, embedded or injected content may request powerful browser features such as camera, microphone or location.",
    fix: "Send a Permissions-Policy that disables the features your site does not use.",
    modes: LIVE,
    tags: ["headers"],
  },
  {
    id: "WEB-L07",
    agent: AGENT,
    title: "Server reflects any Origin and allows credentials (CORS)",
    severity: "high",
    cwe: "CWE-942",
    owasp: "A05",
    summary: "The live server echoes an attacker-chosen Origin in Access-Control-Allow-Origin and also allows credentials, so any website can make authenticated requests as the visitor and read the responses.",
    fix: "Validate the Origin against an explicit allow-list instead of reflecting it, and never combine a reflected origin with credentials.",
    modes: LIVE,
    tags: ["cors"],
  },
  {
    id: "WEB-L08",
    agent: AGENT,
    title: "Cookies are missing security flags",
    severity: "low",
    cwe: "CWE-614",
    owasp: "A05",
    summary: "Some cookies are set without Secure, HttpOnly or SameSite. Without HttpOnly an injected script can steal them; without Secure they travel over plain HTTP. Severity rises to medium for session-like cookies.",
    fix: "Set Secure, HttpOnly and SameSite=Lax (or Strict) on every cookie, especially session cookies.",
    modes: LIVE,
    tags: ["cookies"],
  },
  {
    id: "WEB-L09",
    agent: AGENT,
    title: "Source maps are publicly reachable",
    severity: "medium",
    cwe: "CWE-540",
    owasp: "A05",
    summary: "The site's JavaScript points to .map files anyone can download, and they contain the original source code.",
    fix: "Stop publishing source maps in production or serve them only to authenticated tooling.",
    modes: LIVE,
    tags: ["info-disclosure"],
  },
  {
    id: "WEB-L10",
    agent: AGENT,
    title: "Sensitive file is publicly readable",
    severity: "high",
    cwe: "CWE-538",
    owasp: "A05",
    summary: "A well-known sensitive path (.env, .git, wp-config backup, .DS_Store, phpinfo) returns the real file's contents. Severity is critical when secrets are present and medium for low-impact files.",
    fix: "Remove the file from the web root, block the path in your server config, and rotate any secrets it contained.",
    modes: LIVE,
    tags: ["exposure", "secrets"],
  },
  {
    id: "WEB-L11",
    agent: AGENT,
    title: "Server shows detailed error pages",
    severity: "medium",
    cwe: "CWE-209",
    owasp: "A05",
    summary: "Requesting a nonexistent path returns a stack trace or framework debug page, revealing file paths, versions and internals to attackers.",
    fix: "Disable debug mode in production and return a generic error page.",
    modes: LIVE,
    tags: ["info-disclosure"],
  },
];
