import type { Mode, Severity } from "../../core/types.js";
import type { RuleMeta } from "../../rules/types.js";

const AGENT = "database-guard";
const STATIC: readonly Mode[] = ["static"];

function rule(
  id: string, severity: Severity, cwe: string, title: string, summary: string, fix: string,
  extra: { modes?: readonly Mode[]; tags?: readonly string[] } = {},
): RuleMeta {
  return {
    id, agent: AGENT, title, severity, cwe, owasp: "A01", summary, fix,
    modes: extra.modes ?? STATIC, ...(extra.tags ? { tags: extra.tags } : {}),
  };
}

/** Catalog entries for every rule this agent can raise. Keep in sync with the agent's ruleIds. */
export const RULES: readonly RuleMeta[] = [
  rule("DB-001", "critical", "CWE-862", "Table without Row Level Security",
    "A table in the public schema never has Row Level Security enabled. Supabase exposes public tables through its REST API and the anon key ships in the frontend, so anyone can read, change or delete every row.",
    "ALTER TABLE ... ENABLE ROW LEVEL SECURITY and add owner-scoped policies using (select auth.uid()).", { tags: ["supabase", "rls"] }),
  rule("DB-002", "low", "CWE-284", "RLS enabled but no policies",
    "RLS is enabled on a table that has no policy, so only the service role can use it. The setup is unfinished and may later be 'fixed' with a wide-open policy.",
    "Add explicit owner-scoped policies for each operation the app needs.", { tags: ["supabase", "rls"] }),
  rule("DB-003", "high", "CWE-862", "Policy allows everyone (USING true)",
    "A permissive policy uses USING (true) or WITH CHECK (true) for anon, authenticated or public on a table that holds user data. Every row is readable or writable by anyone in those roles. Restrictive policies are ignored because they only narrow access.",
    "Drop the policy and replace it with one comparing auth.uid() to the owner column.", { tags: ["supabase", "rls"] }),
  rule("DB-004", "medium", "CWE-284", "Policy never checks who the user is",
    "A policy on a table with an owner column never references auth.uid() or auth.jwt(), so it cannot tell users apart and signed-in users may reach each other's rows.",
    "Scope the policy to (select auth.uid()) = <owner column>.", { tags: ["supabase", "rls"] }),
  rule("DB-005", "high", "CWE-269", "SECURITY DEFINER function without fixed search_path",
    "A SECURITY DEFINER function runs with its owner's privileges but does not pin search_path, so a user who can create objects in an earlier schema can hijack what it calls and escalate privileges.",
    "Add SET search_path = '' to the function and schema-qualify every object inside it.", { tags: ["supabase", "postgres"] }),
  rule("DB-006", "high", "CWE-284", "Write privileges granted to anon",
    "A GRANT gives INSERT/UPDATE/DELETE/TRUNCATE (or ALL) on tables to the anon role, which anyone with the public key can use. Any RLS gap then becomes an unauthenticated write.",
    "REVOKE the write privileges from anon and rely on RLS policies for authenticated users.", { tags: ["supabase", "grants"] }),
  rule("DB-007", "medium", "CWE-284", "Public storage bucket",
    "A storage bucket (from SQL or supabase/config.toml) is public, so every file is downloadable by anyone who has or guesses the URL. That is fine for logos but not for avatars, documents or receipts.",
    "Make the bucket private, store files under a <user id>/ prefix, add owner-scoped storage policies and serve signed URLs.", { tags: ["supabase", "storage"] }),
  rule("DB-010", "critical", "CWE-284", "Firebase Firestore / Realtime Database rules open to everyone",
    "Firestore or Realtime Database rules allow reads or writes to anyone (if true) or only until a test-mode expiry date. Once the date has passed the rule is reported at medium severity: the database is closed now but was open, and the usual panic fix reopens it.",
    "Require request.auth != null plus an ownership check (request.auth.uid == userId) and remove 'if true' and request.time expiries.", { tags: ["firebase", "rules"] }),
  rule("DB-011", "critical", "CWE-284", "Firebase Cloud Storage rules open to everyone",
    "Cloud Storage rules allow anyone, signed in or not, to read or write every file, or keep that access open until a test-mode expiry date.",
    "Restrict storage rules to the signed-in owner's own folder and remove 'if true' and expiry dates.", { tags: ["firebase", "rules", "storage"] }),
  rule("DB-012", "critical", "CWE-639", "Authorization based on user_metadata",
    "A policy or SECURITY DEFINER role check reads user_metadata / raw_user_meta_data, which the signed-in user can edit themselves (Supabase linter 0015). Any user can grant themselves admin. app_metadata is the safe alternative and is never flagged.",
    "Use app_metadata (server-written) or a roles table that users cannot write.", { tags: ["supabase", "rls", "splinter-0015"] }),
  rule("DB-013", "high", "CWE-269", "Users can edit their own privilege columns",
    "A table has a column such as role, is_admin, credits, plan or balance and an own-row UPDATE policy without column protection. Any user can call the API and set those columns on their own row. High for role/admin columns, medium for credits, plan and billing columns.",
    "REVOKE UPDATE on the table and GRANT UPDATE only on the columns users may edit, or guard the column with a BEFORE UPDATE trigger.", { tags: ["supabase", "rls", "privilege-escalation"] }),
  rule("DB-014", "high", "CWE-862", "SECURITY DEFINER function callable by anon/authenticated",
    "A SECURITY DEFINER function in the public schema is never revoked from anon/authenticated, so anyone can call it through /rest/v1/rpc with the public key and bypass RLS (Supabase linter 0028/0029). It is worse when it takes a uuid and never checks auth.uid().",
    "REVOKE EXECUTE from public, anon and authenticated, or check auth.uid() inside and move it out of the exposed schema.", { tags: ["supabase", "postgres", "splinter-0028"] }),
  rule("DB-015", "high", "CWE-284", "View bypasses RLS or exposes auth.users",
    "A view in the public schema lacks security_invoker, so it runs with its owner's rights and bypasses RLS on the tables it reads (linter 0010). It is critical when it selects from auth.users (linter 0002).",
    "ALTER VIEW ... SET (security_invoker = true), or REVOKE SELECT from anon and authenticated.", { tags: ["supabase", "views", "splinter-0010"] }),
  rule("DB-016", "high", "CWE-862", "Policies exist but RLS is never enabled",
    "A table has policies but Row Level Security is never enabled on it, so the policies are not enforced and the table is open to anyone with the anon key (linter 0007). The author believes it is protected.",
    "ALTER TABLE ... ENABLE ROW LEVEL SECURITY.", { tags: ["supabase", "rls", "splinter-0007"] }),
  rule("DB-017", "medium", "CWE-284", "Policy only requires a signed-in user",
    "A policy on a table with an owner column only checks auth.uid() IS NOT NULL or auth.role() = 'authenticated'. Sign-up is free, so every account can reach every user's rows.",
    "Compare auth.uid() to the owner column instead of only checking sign-in.", { tags: ["supabase", "rls"] }),
  rule("DB-018", "high", "CWE-862", "Unsafe storage.objects policy",
    "A storage.objects policy lets users insert, update or delete files without an owner or folder check (high), or lets anyone list every file of a public bucket with a bare bucket_id check (medium, linter 0025).",
    "Scope write policies with (storage.foldername(name))[1] = auth.uid()::text and drop SELECT policies on public buckets.", { tags: ["supabase", "storage", "splinter-0025"] }),
  rule("DB-019", "high", "CWE-200", "Sensitive columns exposed by a broad read policy",
    "A public table has columns named like password, api_key, secret, token, otp, ssn or refresh_token and a SELECT policy for anon/authenticated without an owner check, so the secrets can be harvested through the REST API (linter 0023).",
    "Revoke column access from anon/authenticated or move the secrets to a table only the service role can read.", { tags: ["supabase", "rls", "splinter-0023"] }),
  rule("DB-020", "high", "CWE-306", "Edge Function with verify_jwt = false and no own authentication",
    "supabase/config.toml disables JWT verification for an Edge Function whose code has no auth.getUser / getClaims / jwtVerify / webhook signature / shared-secret check, so anyone can invoke it.",
    "Set verify_jwt = true, or verify the caller (signature, JWT or secret) inside the function.", { tags: ["supabase", "edge-functions"] }),
  rule("DB-021", "high", "CWE-287", "Anonymous sign-ins reach 'to authenticated' policies",
    "Anonymous sign-ins are enabled (config.toml or signInAnonymously in code) and a policy granted 'to authenticated' neither checks is_anonymous nor ties rows to the caller, so unregistered visitors get authenticated-level access.",
    "Add an is_anonymous check (a restrictive policy works) or scope the policy with auth.uid().", { tags: ["supabase", "auth"] }),
  rule("DB-022", "high", "CWE-285", "Firebase rules only require sign-in on a wildcard path",
    "Firestore/Storage rules allow request.auth != null (or RTDB auth != null) on a wildcard match or at the database root. Sign-up is public, so 'logged in' means anyone, and every user's data is readable or writable.",
    "Compare request.auth.uid with the owner (path variable or resource.data) on every user-data path.", { tags: ["firebase", "rules"] }),
  rule("DB-L01", "critical", "CWE-862", "Supabase table readable with the public key (live)",
    "A live read-only probe using only the anon key returned a row from a table, proving anyone can download it. Only table and column names are recorded.",
    "Enable RLS on the table and add owner-scoped policies.", { modes: ["live"], tags: ["supabase", "live"] }),
  rule("DB-L02", "critical", "CWE-284", "Firestore collection readable without sign-in (live)",
    "A live read-only request returned a document from a Firestore collection without authentication. Only collection and field names are recorded.",
    "Require request.auth != null and ownership checks in firestore.rules, then deploy them.", { modes: ["live"], tags: ["firebase", "live"] }),
];
